web:
  build: .
  ports:
    - "9292:9292"
  links:
    - redis_db

redis_db:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - 'redis:/data'
    ports:
        - "6379:6379"
